receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [1ms, 2ms, 5ms, 10ms, 20ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s]
    dimensions:
      - name: http.method
      - name: http.status_code

exporters:
  otlp/jaeger:
    endpoint: "jaeger:14317" # Export to jaeger container directly
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889" # Exposes metrics for Prometheus to scrape
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
