global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['localhost:14269'] # Jaeger's admin port which exposes /metrics
