package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"pum-go/pkg/external"
)

// NetworkEquipment is the resolver for the networkEquipment field.
func (r *queryResolver) NetworkEquipment(ctx context.Context) ([]*external.GNetworkEquipment, error) {
	return r.Provider.GetNetworkEquipment(ctx)
}

// Pdus is the resolver for the pdus field.
func (r *queryResolver) Pdus(ctx context.Context) ([]*external.Gpdu, error) {
	return r.Provider.GetPDUs(ctx)
}

// Computers is the resolver for the computers field.
func (r *queryResolver) Computers(ctx context.Context) ([]*external.GComputer, error) {
	return r.Provider.GetComputers(ctx)
}

// Hosts is the resolver for the hosts field.
func (r *queryResolver) Hosts(ctx context.Context) ([]*external.ZHost, error) {
	return r.Provider.GetHosts(ctx)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
