package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"pum-go/pkg/models"
)

// SyncInventory is the resolver for the syncInventory field.
func (r *mutationResolver) SyncInventory(ctx context.Context) (string, error) {
	err := r.Sync.Run(ctx)
	if err != nil {
		return "Failed", err
	}
	return "Success", nil
}

// Switches is the resolver for the switches field.
func (r *queryResolver) Switches(ctx context.Context) ([]*models.Switch, error) {
	var switches []*models.Switch
	r.DB.WithContext(ctx).Preload("Ports").Find(&switches)
	return switches, nil
}

// Ports is the resolver for the ports field.
func (r *queryResolver) Ports(ctx context.Context) ([]*models.SwitchPort, error) {
	var ports []*models.SwitchPort
	r.DB.WithContext(ctx).Find(&ports)
	return ports, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// Switch is the resolver for the switch field.
func (r *queryResolver) Switch(ctx context.Context, id string) (*models.Switch, error) {
	var sw models.Switch
	if err := r.DB.WithContext(ctx).Preload("Ports").First(&sw, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &sw, nil
}

// Switch returns SwitchResolver implementation.
func (r *Resolver) Switch() SwitchResolver { return &switchResolver{r} }

type switchResolver struct{ *Resolver }

func (r *switchResolver) NodeID(ctx context.Context, obj *models.Switch) (int, error) {
	return int(obj.NodeID), nil
}

func (r *switchResolver) Ports(ctx context.Context, obj *models.Switch) ([]*models.SwitchPort, error) {
	var ports []*models.SwitchPort
	r.DB.WithContext(ctx).Where("switch_id = ?", obj.ID).Find(&ports)
	return ports, nil
}
