package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"pum-go/pkg/models"
)

// SyncInventory is the resolver for the syncInventory field.
func (r *mutationResolver) SyncInventory(ctx context.Context) (string, error) {
	err := r.Sync.Run()
	if err != nil {
		return "Sync failed", err
	}
	return "Sync successful", nil
}

// Ports is the resolver for the ports field.
func (r *queryResolver) Ports(ctx context.Context) ([]*models.SwitchPort, error) {
	var ports []*models.SwitchPort
	r.DB.Find(&ports)
	return ports, nil
}

// Switches is the resolver for the switches field.
func (r *queryResolver) Switches(ctx context.Context) ([]*models.Switch, error) {
	var switches []*models.Switch
	r.DB.Find(&switches)
	return switches, nil
}

// NodeID is the resolver for the nodeId field.
func (r *switchResolver) NodeID(ctx context.Context, obj *models.Switch) (int, error) {
	return int(obj.NodeID), nil
}

// GlpiID is the resolver for the glpiId field.
func (r *switchResolver) GlpiID(ctx context.Context, obj *models.Switch) (*string, error) {
	return &obj.GlpiID, nil
}

// Ports is the resolver for the ports field.
func (r *switchResolver) Ports(ctx context.Context, obj *models.Switch) ([]*models.SwitchPort, error) {
	var ports []*models.SwitchPort
	r.DB.Where("switch_id = ?", obj.ID).Find(&ports)
	return ports, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Switch returns SwitchResolver implementation.
func (r *Resolver) Switch() SwitchResolver { return &switchResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type switchResolver struct{ *Resolver }
