// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Product struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Description      *string `json:"description,omitempty"`
	Address          *string `json:"address,omitempty"`
	State            *string `json:"state,omitempty"`
	Long             *string `json:"long,omitempty"`
	Lat              *string `json:"lat,omitempty"`
	Geo              *string `json:"geo,omitempty"`
	Operate          bool    `json:"operate"`
	GlpiUUID         *string `json:"glpiUUID,omitempty"`
	SequentialNumber int     `json:"sequentialNumber"`
	PouType          string  `json:"pouType"`
	Region           string  `json:"region"`
}

type Query struct {
}
