package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"pum-go/pkg/models"
	"pum-go/services/product/graph/model"
	"strconv"
)

// SyncProducts is the resolver for the syncProducts field.
func (r *mutationResolver) SyncProducts(ctx context.Context) (string, error) {
	err := r.Sync.Run()
	if err != nil {
		return "Sync failed", err
	}
	return "Sync successful", nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	var products []models.Product
	if err := r.DB.Find(&products).Error; err != nil {
		return nil, err
	}
	var gqlProducts []*model.Product
	for _, p := range products {
		gqlProducts = append(gqlProducts, &model.Product{
			ID:               strconv.Itoa(int(p.ID)),
			Name:             p.Name,
			Description:      &p.Description,
			Address:          &p.Address,
			State:            &p.State,
			Long:             &p.Long,
			Lat:              &p.Lat,
			Geo:              &p.Geo,
			Operate:          p.Operate,
			GlpiUUID:         &p.GlpiUUID,
			SequentialNumber: p.SequentialNumber,
			PouType:          p.PouType,
			Region:           p.Region,
		})
	}
	return gqlProducts, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	var p models.Product
	if err := r.DB.First(&p, id).Error; err != nil {
		return nil, err
	}
	return &model.Product{
		ID:               strconv.Itoa(int(p.ID)),
		Name:             p.Name,
		Description:      &p.Description,
		Address:          &p.Address,
		State:            &p.State,
		Long:             &p.Long,
		Lat:              &p.Lat,
		Geo:              &p.Geo,
		Operate:          p.Operate,
		GlpiUUID:         &p.GlpiUUID,
		SequentialNumber: p.SequentialNumber,
		PouType:          p.PouType,
		Region:           p.Region,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
