package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"pum-go/pkg/external"
	"pum-go/pkg/models"
	"strconv"
)

// SyncProducts is the resolver for the syncProducts field.
func (r *mutationResolver) SyncProducts(ctx context.Context) (string, error) {
	err := r.Sync.Run()
	if err != nil {
		return "Sync failed", err
	}
	return "Sync successful", nil
}

// ID is the resolver for the id field.
func (r *productResolver) ID(ctx context.Context, obj *models.Product) (string, error) {
	return strconv.Itoa(int(obj.ID)), nil
}

// Problems is the resolver for the problems field.
func (r *productResolver) Problems(ctx context.Context, obj *models.Product) ([]*external.ZProblem, error) {
	hosts, _ := r.Provider.GetHosts(ctx)
	for _, h := range hosts {
		// Mock mapping: Rack 1 -> MSK-SW-01
		if (obj.Name == "Rack 1" && h.Name == "MSK-SW-01") || (obj.Name == "Rack 2" && h.Name == "SPB-SW-02") {
			return h.Problems, nil
		}
		if h.Name == obj.Name {
			return h.Problems, nil
		}
	}
	return []*external.ZProblem{}, nil
}

// Status is the resolver for the status field.
func (r *productResolver) Status(ctx context.Context, obj *models.Product) (int, error) {
	hosts, _ := r.Provider.GetHosts(ctx)
	for _, h := range hosts {
		if (obj.Name == "Rack 1" && h.Name == "MSK-SW-01") || (obj.Name == "Rack 2" && h.Name == "SPB-SW-02") {
			return h.Status, nil
		}
		if h.Name == obj.Name {
			return h.Status, nil
		}
	}
	return 1, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*models.Product, error) {
	var products []*models.Product
	if err := r.DB.Find(&products).Error; err != nil {
		return nil, err
	}
	return products, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*models.Product, error) {
	var p models.Product
	if err := r.DB.First(&p, id).Error; err != nil {
		return nil, err
	}
	return &p, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
